### DISCUSSION TITLE
这皮肤真相见恨晚

### DISCUSSION THREAD

**Discussion by luminosara** [LufsX/rime#21] [General]
我自己在Windows小狼毫上也用着类似的皮肤，当时改来改去花了好十几个小时，当时用的fxliang的分支也没有和小狼毫主仓库合并，在皮肤配置上踩了好多坑😂没想到过了好几个月不仅fxliang的分支和主仓库合并了，而且GitHub还给我推了类似的皮肤 ~~看来还是遇到Rime太早~~

我来贴一下我自己用的皮肤配置，有需要可以参考或者增加到配置里。需要使用小狼毫在action里面的最新构建。 ~~字体和候选栏比较大很老年模式，有需要自己调小一下~~

![image](https://github.com/LufsX/rime/assets/87697012/d2b93de5-77f3-448f-a44d-d64240e1c48a)

![image](https://github.com/LufsX/rime/assets/87697012/8baa36a5-7c16-4793-ad86-6a82ebbe9a35)

```
patch:
  "preset_color_schemes/win10":
    author: me
    back_color: 0xF3F3F3
    border_color: 0xDBDCDC
    candidate_text_color: 0x000000
    hilited_candidate_back_color: 0xFFD8A6 #取色来自win10默认，有需要自己调一下，记得是BGR
    hilited_label_color: 0x6F6F6F
    hilited_mark_color: 0x00000000
    label_color: 0x6F6F6F
    name: Windows10
    shadow_color: 0x4DFDFDFD
    text_color: 0x000000
  "style/capture_by_click": true #这里之后的引号可有可无，我改的时候没删，控制鼠标选词
  "style/color_scheme": win10
  "style/font_point": 14
  "style/horizontal": true
  "style/inline_preedit": true
  "style/label_font_point": 14
  "style/label_format": "%s"
  "style/layout/border_width": 2 #边框线粗细
  "style/layout/candidate_spacing": 50 
  "style/layout/corner_radius": 10 #高亮框圆角
  "style/layout/hilite_padding": 18
  "style/layout/hilite_spacing": 17 #候选词和序号之间的距离，没找到能控制高亮框的长度的，导致高亮框右侧边距有点小
  "style/layout/margin_x": 17
  "style/layout/margin_y": 17
  "style/layout/round_corner": 10 #候选框圆角
  "style/layout/shadow_offset_x": 5
  "style/layout/shadow_offset_y": 4
  "style/layout/shadow_radius": 10
  "style/mark_text": " ​​" 
```

对最后一个的注释：找不到和win11类似的前面有个|引导线，如果这里是用|显示的时候不是居中就很丑...如果win11主题不加引导线又怪怪的，所以就没放win11主题，其实只要把高亮框高度调低就行，但是由于控制不了高亮框的长度，所以emmm...如果想要和win10一模一样的网上有很多，这里主要是类似apathy，在win10默认上改了圆角和阴影
