### DISCUSSION TITLE
[feature request] 做了一些 MDL2 风格的 theme

### DISCUSSION THREAD

**Discussion by fbewivpjsbsby** [LufsX/rime#29] [General]
### 相关
weasel.custom.yaml
```yaml
patch:
  __include: "[filename]:/patch/style/[name]"
```

[filename].yaml
```yaml
patch:
    style:
      win10MDLgolbal:
      __include: patch/theme
      style/inline_preedit: true
      style/horizontal: true
      style/label_format: "%s"
      style/font_point: 13
      style/label_font_point: 9
      # style/layout/min_width: 160
      # style/layout/min_height: 0
      style/layout/border_width: 1
      style/layout/margin_x: 15
      style/layout/margin_y: 10
      style/layout/spacing: 10
      style/layout/candidate_spacing: 30
      style/layout/corner_radius: 0
      style/layout/round_corner: 0
      style/layout/hilite_spacing: 5
      # style/layout/hilite_padding: 15
      style/layout/hilite_padding_x: 27
      style/layout/hilite_padding_y: 15
      # style/layout/shadow_offset_y: 4 # 阴影 Y 轴偏移
      # style/layout/shadow_radius: 10 # 阴影半径

      win10MDLayaya:
        __include: patch/style/win10MDLgolbal
        style/color_scheme: win10_MDL_ayaya_weasel

      win10MDLdeepgrep:
        __include: patch/style/win10MDLgolbal
        style/color_scheme: win10_MDL_deepgrey

      win10MDLblue:
        __include: patch/style/win10MDLgolbal
        style/color_scheme: win10_MDL_blue
      
      win10MDLdarkblue:
        __include: patch/style/win10MDLgolbal
        style/color_scheme: win10_MDL_darkblue
    theme:
      preset_color_schemes/win10_MDL_ayaya_weasel:
      back_color: 0xFFFFFF
      candidate_text_color: 0x121212
      comment_text_color: 0x8E8E8E
      hilited_candidate_back_color: 0xECE4FC
      hilited_label_color: 0xB18FF4 # hilited_candidate_label_color: 0xB18FF4
      hilited_candidate_text_color: 0x7A40EC
      label_color: 0x888785
      text_color: 0x8100EB
      # candidate_format: "%c\u2005%@ " # not support

    preset_color_schemes/win10_MDL_deepgrey:  # 在配色方案列表裏加入標識爲 starcraft 的新方案
      name: Windows10
      author: me
      text_color: 0x000000             # 編碼行文字顏色，24位色值，用十六進制書寫方便些，順序是藍綠紅0xBBGGRR
      candidate_text_color: 0x000000   # 候選項文字顏色，當與文字顏色不同時指定
      back_color: 0xFFFFFF             # 底色
      border_color: 0x7E7969           # 邊框顏色，與底色相同則爲無邊框的效果
      hilited_text_color: 0xFFFFFF     # 高亮文字，即與當前高亮候選對應的那部份輸入碼
      hilited_back_color: 0x7E7969     # 設定高亮文字的底色，可起到凸顯高亮部份的作用
      hilited_candidate_text_color: 0xFFFFFF  # 高亮候選項的文字顏色，要醒目！
      hilited_candidate_back_color: 0x7E7969  # 高亮候選項的底色，若與背景色不同就會顯出光棒
      hilited_label_color: 0xffffff
      comment_text_color: 0x888888     # 註釋
      hilited_comment_text_color: 0xffffff  # 高亮區域註釋
    preset_color_schemes/win10_MDL_blue:
      candidate_text_color: 0x000000
      comment_text_color: 0x888888
      text_color: 0x000000
      back_color: 0xffffff
      border_color: 0xcc8f29
      hilited_text_color: 0x000000
      hilited_back_color: 0xffffff
      hilited_candidate_text_color: 0xffffff
      hilited_candidate_back_color: 0xcc8f29
      hilited_comment_text_color: 0xffffff
      hilited_label_color: 0xffffff
      label_color: 0x888888
      name: "Windows 10"
    preset_color_schemes/win10_MDL_darkblue:
      candidate_text_color: 0xf2f2f2
      comment_text_color: 0x888888
      text_color: 0xffffff
      back_color: 0x1f1f1f
      border_color: 0xa37220
      hilited_text_color: 0xffffff
      hilited_back_color: 0x1f1f1f
      hilited_candidate_text_color: 0xf2f2f2
      hilited_candidate_back_color: 0xa37220
      hilited_comment_text_color: 0xffffff
      hilited_label_color: 0xf2f2f2
      label_color: 0x888888
      name: "Windows 10"
```
