### ISSUE TITLE
如何在小鶴雙拼輸入中進行簡體和繁體的轉換？

### ISSUE THREAD

**Issue by Lenoix** [LufsX/rime#12]
F2切換輸入方案後，進入小鶴雙拼設置，有西文中文全角半角轉換，但沒有簡繁轉換，請問如何添加？

**Comment by LufsX** [comment]
以前是有简繁转化的，但日常折腾的话用户词频会出些奇奇怪怪的东西，所以干脆剔除了简繁转化

嘛，加回去也算简单的

1. 在方案文件中的 `switches` 中添加
```yaml
  - name: traditionalization
    states: [ 简, 繁 ]
    # reset: 0 # 默认值
```
2. 在方案文件中的 `engine` 下的 `filters` 添加
```yaml
    - simplifier@traditionalize # 简繁转化
    - uniquifier # 去重
```
3. 在方案文件中添加
```yaml
traditionalize:
  option_name: traditionalization
  opencc_config: s2t.json # s2t.json | s2hk.json | s2tw.json | s2twp.json
  tips: all # 转换提示: all 显示 | char 仅单字显示 | none 不显示。
```
