### ISSUE TITLE
请教一下

### ISSUE THREAD

**Issue by goldenapple1** [LufsX/rime#28]
配置中的上下文推测是哪里来的数据？要怎么才能单独挂载到输入法里（如果我只想挂载这一个功能）？

**Comment by LufsX** [comment]
长句模型是剪裁过的，复制于 [placeless/squirrel_config](https://github.com/placeless/squirrel_config/blob/master/2021/zh-hans-t-essay-bgw.gram)

未剪裁的原始文件在 [lotem/rime-octagram-data](https://github.com/lotem/rime-octagram-data)

挂载方法直接输入法方案内加入以下项即可
```yaml
grammar:
  language: zh-hans-t-essay-bgw
```

也可见 [lotem/rime-octagram-data](https://github.com/lotem/rime-octagram-data) 内的 [grammar.yaml](https://github.com/lotem/rime-octagram-data/blob/master/grammar.yaml)

**Comment by goldenapple1** [comment]
感谢回复，但我注意到schema文件里还有一段这样的：

```
translator:
  dictionary: extended
  preedit_format:
    # - xform/ // # 去掉上屏字符间空格
  prism: lufs_dpy
  contextual_suggestions: true
  max_homophones: 7
```

我猜测 contextual_suggestions也需要开启？而且不太清楚prism的用途是什么
