### ISSUE TITLE
如何设置单击 shift 切换中英文，shift + 字母输入大写字母

### ISSUE THREAD

**Issue by n-WN** [LufsX/rime#36]
目前哪怕是设置单击 `shift` 切换中英文都有问题

`default.yaml` 如下

```yaml
ascii_composer:
  # ascii_composer/switch_key/Shift_L: commit_code
  good_old_caps_lock:
  switch_key:
    Shift_L: commit_code
    Shift_R: commit_code # macOS 上此项无效，Windows 可用右 Shift 切换中英输入
    Control_L: noop
    Control_R: noop # macOS 上此项无效，Windows 上可自行定义
    Caps_Lock: commit_code
    Eisu_toggle: clear
```
